env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - airbnb-base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
globals:
  test: readonly
  expect: readonly
plugins:
  - '@typescript-eslint'
rules:
  ### Default Rules ###
  no-console: 0

  ### import ###
  import/prefer-default-export: 0
