env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - airbnb-base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
globals:
  test: readonly
  expect: readonly
plugins:
  - '@typescript-eslint'
rules:
  ### Default Rules ###
  no-console: 0
  no-unused-vars: 0
  no-extra-semi: 0
  semi: 0
  class-methods-use-this: 0
  no-plusplus: 0
  no-continue: 0
  no-param-reassign:
    - error
    - props: false

  ### Typescript ###
  '@typescript-eslint/no-extra-semi': error
  '@typescript-eslint/semi': error

  ### import ###
  import/prefer-default-export: 0
  import/extensions: 0
  import/no-unresolved: 0
